name: ztdl
channels:
- defaults
dependencies:
- python=3.7.*
- pip==19.0.*
- numpy==1.16.*
- jupyter==1.*
- matplotlib==3.0.*
- scikit-learn==0.20.*
- cython==0.29.*
- pip:
  - tensorflow==2.0.0-alpha0
